basepath = "."

locales = [
  "de",
  "es",
  "fr",
  "it",
  "ru",
  "vi",
]
[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
