site_name: Firefox Lockbox for Android
site_description: Documentation for Firefox Lockbox for Android application
theme: readthedocs
repo_name: GitHub
repo_url: https://github.com/mozilla-lockbox/lockbox-android

pages:
- 'Introduction': 'index.md'
- 'Contributing': 'contributing.md'
- 'Release Notes': 'release-notes.md'
- 'Telemetry and Metrics': 'metrics.md'
- 'Developer Guides':
  - 'Build and Install': 'install.md'
  - 'Flux Architecture': 'architecture/flux.md'
  - 'Using Keys and Biometrics': 'architecture/sec-apis.md'
  - 'Accessibility': 'accessibility.md'
  - 'Release Instructions': 'releases.md'
